spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
  application:
    name: service

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:database/data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: testPassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 0

springdoc:
  swagger-ui:
    csrf:
      enabled: true

delay:
  getOne: 2000
  getAll: 3000
  delete: 2000
  update: 2000
  add: 100